### ISSUE TITLE
Auto browser cache refresh

### ISSUE THREAD

**Issue by Sebyrem** [PiotrMachowski/lovelace-html-card#11]
Hello team
I use the card to read mp4 file previously saved locally from my camera. My camera is updating same file name each event time. I can read the file the card works but as my camera is updating the file (same name same extension) I can't get to play the new version I always get the same. It seams that it plays always the cache version instead of the file itself. Is there any way to au refresh the page to clean the cache and to reset play. Many thanks. Seb

**Comment by PiotrMachowski** [comment]
I don't think this is something that can be handled from a card. How do you display the mp4 file?

**Comment by Sebyrem** [comment]
Like this 

content: |  <video id=vid1 class="video-js" width=450 height=260 controls autoplay=true>   <source      src="/local/porte.mp4"      type="video/mp4">   </video>  <script> var player = videojs('vid1'); player.logo({    image: 'http://YOUR_IP:8123/local/murray-logo.png'title: Last Ding Porte d'entr%C3%A9etype: custom:html-card

**Comment by Sebyrem** [comment]
Is there any way to force the card to reload the file each time activated ?

**Comment by Sebyrem** [comment]
Adding this line : ?t=[[sensor.time]]'

Is that correct ?

**Comment by PiotrMachowski** [comment]
Yes, assuming you have `sensor.time` entity

**Comment by Sebyrem** [comment]
Sorry but what is a sensor.time ?

**Comment by PiotrMachowski** [comment]
https://www.home-assistant.io/integrations/time_date/
