### ISSUE TITLE
doesnt process jinja2 or javascript

### ISSUE THREAD

**Issue by magiva** [PiotrMachowski/lovelace-html-card#13]
in my markdown cards i setup variables with jinja2 to be included in a html table but i cant color the table how i like
i was hoping this would achieve it, it colors the table but doesnt process jinja2 or js - can it ?

**Comment by PiotrMachowski** [comment]
JS is not supported, jinja is supported by built-in markdown card and this card https://github.com/PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card

**Comment by magiva** [comment]
Perfect
