### ISSUE TITLE
Card refreshes when any device changes its state, add setting to allow disabling refresh

### ISSUE THREAD

**Issue by yevon** [PiotrMachowski/lovelace-html-card#2]
It would be very nice to add a setting to dissallow card refresh, because every time an entity updates its state, the card gets refreshed and it isn't what you want all times. For example, I was trying to play a youtube video, and every time an entity gets updated, the video starts again.

**Comment by PiotrMachowski** [comment]
Check out latest version of card, I have optimized refreshing to occur only when entity used in template updates its state.
