### ISSUE TITLE
Support templates?

### ISSUE THREAD

**Issue by bruxy70** [PiotrMachowski/lovelace-html-card#3]
This is great. Any chance to add support for templates, so that I can make calculations with sensor values? I have a sensor with an attribute that has line breaks, I am thinking to send it to regex to replace `"\n"` by `"<br/>"`

I guess I can create template sensors to show the attribute, but it does not feel right to create a bunch of sensors just to do text formatting...

Or perhaps at least doing the new line replacement in your plugin, so that it renders new lines...When I show the attribute in the developer tools states or template, it breaks the lines on new line character, but the html-card does not do that. So I think the correct behavior would be to make a new line.
Thanks

**Comment by PiotrMachowski** [comment]
I am glad you like my card. Functions in templates are not easy to implement, so the easiest way for me would be to replace `\n` by `</br>`.

**Comment by bruxy70** [comment]
Thanks. It works in markdown mod BTW.

**Comment by PiotrMachowski** [comment]
Well, it turned out better than expected, you have inspired me to create new card: [HTML Template card](https://github.com/PiotrMachowski/Home-Assistant-Lovelace-HTML-Template-card). It should be the best solution for your needs.
