### ISSUE TITLE
How to show html from wget/curl?

### ISSUE THREAD

**Issue by UksusoFF** [PiotrMachowski/lovelace-html-card#4]
Hi! Any way to do subject in this plugin?

I'm try:
```
  - platform: command_line
    name: Name
    command: "curl 'http://example.com/xml_bridge.php'"
    scan_interval: 86400
```

But got here:
```homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.tosamara. State max length is 255 characters.```

**Comment by PiotrMachowski** [comment]
In Home Assistant entity state can have max 255 characters, so you cant't use a sensor to curl a website. You can use [iframe card](https://www.home-assistant.io/lovelace/iframe/) instead.

**Comment by UksusoFF** [comment]
@PiotrMachowski can't use iframe because POST method used :(

**Comment by PiotrMachowski** [comment]
You can try to save output to a file in www folder and then display it in an iframe (just an idea)

**Comment by UksusoFF** [comment]
@PiotrMachowski thanks!
