### ISSUE TITLE
TypeError: this._hass.states[id] is undefined

### ISSUE THREAD

**Issue by wlk** [PiotrMachowski/lovelace-html-card#5]
Following error happens after adding MPK cards and I go into "Configure UI" section:
```
TypeError: this._hass.states[id] is undefinedhtml-card.js:77:21
    render html-card.js:77
    forEach self-hosted:266
    render html-card.js:66
    set hass html-card.js:16
    value hui-view.ts:61
    value hui-view.ts:334
    value hui-view.ts:68
    r fire_event.ts:76
    va create-card-element.ts:111
```

MPK card configuration (rozkladzik and impk):

```
      - content: |
          <big><center>Odjazdy</center></big>
          [[ sensor.rozkladzik_wroclaw_1972.attributes.html ]]
          <big><center>News</center></big>
          [[ binary_sensor.impk_news.attributes.html ]]
        title: MPK
        type: 'custom:html-card'
```

When viewed in regular view mode (not UI editor), the card doesn't render at all - everything else is OK
When viewed in "UI Editor mode", this error prevents Lovelace from displaying any cards.
After removing widget everything works OK.

**Comment by wlk** [comment]
Error probably appears because https://www.rozkladzik.pl/ is not responding for me:
```
w@desktop ~ $ curl https://www.rozkladzik.pl/
curl: (7) Failed to connect to www.rozkladzik.pl port 443: Connection refused
```

**Comment by PiotrMachowski** [comment]
Integration for Rozkładzik is currently broken, you can follow this issue:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Rozkladzik/issues/2
